services:
  pihole:
    image: pihole/pihole:2025.11.1
    network_mode: service:tailscale
    environment:
      TZ: "Europe/London"
      WEBPASSWORD: "CHANGEME"
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
    depends_on:
      - tailscale

  tailscale:
    image: tailscale/tailscale:v1.92.4
    hostname: pihole
    environment:
      - TS_AUTH_ONCE="true"
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
